server:
  # 项目端口号
  port: 1010

spring:
  application:
    # 项目名称
    name: 'user'
  cloud:
    nacos:
      discovery:
        # Nacos 服务地址
        server-addr: '127.0.0.1:8848'

feign:
  client:
    config:
      # 指定对应微服务名称
      # 这里因为只看 Feign 访问 order 项目的日志，所以就写 order 了
      # 如果把这里的 order 改成 default 那就是所有的微服务访问都生效
      order:
        # 配置日志详情级别
        logger-level: full
        # 连接超时
        connect-timeout: 2000
        # 读取超时
        read-timeout: 2000

logging:
  level:
    com.lynchj.study.user.feign: debug
